# Generated by Django 4.1 on 2023-04-04 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["id"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="categoryproductrel",
            options={
                "verbose_name": "Связь Продукт-Категория",
                "verbose_name_plural": "Связи Продукт-Категория",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["id"],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                height_field=200,
                null=True,
                upload_to="category",
                verbose_name="Изображение",
                width_field=200,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="products.category",
                verbose_name="Надкатегория",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category_path",
            field=models.TextField(verbose_name="Входит в категории"),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="categoryproductrel",
            unique_together={("category", "product")},
        ),
    ]
