# Generated by Django 4.1 on 2023-04-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="preview_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products", width_field=500
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="splash_image",
            field=models.ImageField(blank=True, null=True, upload_to="products"),
        ),
        migrations.AddField(
            model_name="product",
            name="thumb_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products", width_field=100
            ),
        ),
    ]
