# Generated by Django 4.1 on 2023-04-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_preview_image_product_splash_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                height_field="200",
                null=True,
                upload_to="category",
                verbose_name="Изображение",
                width_field="200",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="preview_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products", width_field="500"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="thumb_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products", width_field="100"
            ),
        ),
    ]
