# Generated by Django 4.1 on 2023-04-05 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_product_splash_image_productthumb_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductThumb",
        ),
    ]
