# Generated by Django 4.1 on 2023-04-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_delete_productthumb"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="thumb_image",
        ),
        migrations.AlterField(
            model_name="product",
            name="preview_image",
            field=models.ImageField(blank=True, null=True, upload_to="previews"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="product-images/"),
        ),
    ]
