# Generated by Django 4.1 on 2023-04-05 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_remove_product_thumb_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "verbose_name": "Связь с изображением",
                "verbose_name_plural": "Связь с изображениеми",
            },
        ),
        migrations.AlterField(
            model_name="categoryproductrel",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="products.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="categoryproductrel",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="products.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.BooleanField(default=False, verbose_name="В наличии"),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата добавления"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="previews",
                verbose_name="Фото для превью",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="product-images/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.product",
                verbose_name="Продукт",
            ),
        ),
    ]
