# Generated by Django 4.1 on 2023-04-05 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("paid", "paid"),
                    ("need_approval", "need_approval"),
                    ("shipped", "shipped"),
                    ("delivered", "delivered"),
                    ("refunding", "refunding"),
                    ("refunded", "refunded"),
                ],
                default="draft",
                max_length=255,
                verbose_name="Статус заказа",
            ),
        ),
    ]
