# Generated by Django 4.1 on 2023-04-06 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profileinfo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
