# Generated by Django 4.2 on 2023-04-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_delete_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profileinfo",
            options={
                "verbose_name": "Доп. информация",
                "verbose_name_plural": "Доп. информация",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "Учетная запись",
                "verbose_name_plural": "Учетные записи",
            },
        ),
        migrations.AddField(
            model_name="profileinfo",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profileinfo",
            name="firstname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profileinfo",
            name="lastname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profileinfo",
            name="phonenumber",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
