# Generated by Django 4.2 on 2023-04-08 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0004_alter_profileinfo_options_alter_userprofile_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profileinfo",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="profileinfo",
            name="photo",
        ),
    ]
