# Generated by Django 4.2 on 2023-04-08 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_profileinfo_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileinfo",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="info",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
