# Generated by Django 4.2 on 2023-04-08 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0006_alter_cart_user_alter_cartitem_cart_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "Корзина", "verbose_name_plural": "Корзины"},
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "verbose_name": "Продукт в корзине",
                "verbose_name_plural": "Продукты в корзине",
            },
        ),
    ]
